//
// Created by ludger on 21.01.18.
//

#ifndef FLIGHTMANAGER_DATABASECOMMANDS_H
#define FLIGHTMANAGER_DATABASECOMMANDS_H

const char *createDatabaseCommand = "CREATE TABLE IF NOT EXISTS flights\n"
        "(\n"
        "    Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,\n"
        "    start DATETIME NOT NULL,\n"
        "    end DATETIME\n"
        ");\n"
        "CREATE UNIQUE INDEX IF NOT EXISTS flights_Id_uindex ON flights (Id);\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS flightMode\n"
        "(\n"
        "    FlightId INTEGER NOT NULL,\n"
        "    ResetCount UNSIGNED INTEGER NOT NULL,\n"
        "    Timestamp UNSIGNED INTEGER NOT NULL,\n"
        "\n"
        "    FlightMode UNSIGNED INTEGER NOT NULL,\n"
        "    SeaLevelPressure FLOAT,\n"
        "    DoPressureCompensation BOOLEAN\n"
        ");\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS GpsVelocity\n"
        "(\n"
        "    FlightId INTEGER NOT NULL,\n"
        "    ResetCount UNSIGNED INTEGER NOT NULL,\n"
        "    Timestamp UNSIGNED INTEGER NOT NULL,\n"
        "\n"
        "    Speed FLOAT NOT NULL,\n"
        "    CourseOverGround FLOAT NOT NULL\n"
        ");\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS AirVelocity\n"
        "(\n"
        "    FlightId INTEGER NOT NULL,\n"
        "    ResetCount UNSIGNED INTEGER NOT NULL,\n"
        "    Timestamp UNSIGNED INTEGER NOT NULL,\n"
        "\n"
        "    Speed FLOAT NOT NULL\n"
        ");\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS Position\n"
        "(\n"
        "    FlightId INTEGER NOT NULL,\n"
        "    ResetCount UNSIGNED INTEGER NOT NULL,\n"
        "    Timestamp UNSIGNED INTEGER NOT NULL,\n"
        "\n"
        "    Latitude FLOAT NOT NULL,\n"
        "    Longitude FLOAT NOT NULL,\n"
        "    GpsAltitude FLOAT NOT NULL,\n"
        "    RealTime DATETIME NOT NULL,\n"
        "    NumberOfSatellites UNSIGNED INTEGER NOT NULL\n"
        ");\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS Altitude\n"
        "(\n"
        "    FlightId INTEGER NOT NULL,\n"
        "    ResetCount UNSIGNED INTEGER NOT NULL,\n"
        "    Timestamp UNSIGNED INTEGER NOT NULL,\n"
        "\n"
        "    Altitude FLOAT NOT NULL,\n"
        "    RateOfClimb FLOAT NOT NULL\n"
        ");\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS Attitude\n"
        "(\n"
        "    FlightId INTEGER NOT NULL,\n"
        "    ResetCount UNSIGNED INTEGER NOT NULL,\n"
        "    Timestamp UNSIGNED INTEGER NOT NULL,\n"
        "\n"
        "    CourseMagnetic FLOAT NOT NULL,\n"
        "    Pitch FLOAT NOT NULL,\n"
        "    Roll FLOAT NOT NULL\n"
        ");\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS StaticPressure\n"
        "(\n"
        "    FlightId INTEGER NOT NULL,\n"
        "    ResetCount UNSIGNED INTEGER NOT NULL,\n"
        "    Timestamp UNSIGNED INTEGER NOT NULL,\n"
        "\n"
        "    Pressure FLOAT NOT NULL,\n"
        "    Temperature FLOAT NOT NULL\n"
        ");\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS PitotPressure\n"
        "(\n"
        "    FlightId INTEGER NOT NULL,\n"
        "    ResetCount UNSIGNED INTEGER NOT NULL,\n"
        "    Timestamp UNSIGNED INTEGER NOT NULL,\n"
        "\n"
        "    Pressure FLOAT NOT NULL,\n"
        "    Temperature FLOAT NOT NULL\n"
        ");\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS GyroRaw\n"
        "(\n"
        "    FlightId INTEGER NOT NULL,\n"
        "    ResetCount UNSIGNED INTEGER NOT NULL,\n"
        "    Timestamp UNSIGNED INTEGER NOT NULL,\n"
        "\n"
        "    x FLOAT NOT NULL,\n"
        "    y FLOAT NOT NULL,\n"
        "    z FLOAT NOT NULL\n"
        ");\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS MagRaw\n"
        "(\n"
        "    FlightId INTEGER NOT NULL,\n"
        "    ResetCount UNSIGNED INTEGER NOT NULL,\n"
        "    Timestamp UNSIGNED INTEGER NOT NULL,\n"
        "\n"
        "    x FLOAT NOT NULL,\n"
        "    y FLOAT NOT NULL,\n"
        "    z FLOAT NOT NULL\n"
        ");\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS AccelRaw\n"
        "(\n"
        "    FlightId INTEGER NOT NULL,\n"
        "    ResetCount UNSIGNED INTEGER NOT NULL,\n"
        "    Timestamp UNSIGNED INTEGER NOT NULL,\n"
        "\n"
        "    x FLOAT NOT NULL,\n"
        "    y FLOAT NOT NULL,\n"
        "    z FLOAT NOT NULL\n"
        ");\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS BatteryData\n"
        "(\n"
        "    FlightId INTEGER NOT NULL,\n"
        "    ResetCount UNSIGNED INTEGER NOT NULL,\n"
        "    Timestamp UNSIGNED INTEGER NOT NULL,\n"
        "\n"
        "    Voltage FLOAT NOT NULL,\n"
        "    Current FLOAT NOT NULL\n"
        ");\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS BatteryData\n"
        "(\n"
        "    FlightId INTEGER NOT NULL,\n"
        "    ResetCount UNSIGNED INTEGER NOT NULL,\n"
        "    Timestamp UNSIGNED INTEGER NOT NULL,\n"
        "\n"
        "    Yaw INTEGER NOT NULL,\n"
        "    Pitch INTEGER NOT NULL,\n"
        "    Thrust INTEGER NOT NULL,\n"
        "    Roll INTEGER\n"
        ");\n"
        "\n"
        "CREATE TABLE IF NOT EXISTS CurrentCommand\n"
        "(\n"
        "    FlightId INTEGER NOT NULL,\n"
        "    ResetCount UNSIGNED INTEGER NOT NULL,\n"
        "    Timestamp UNSIGNED INTEGER NOT NULL,\n"
        "\n"
        "    PitchAngle FLOAT,\n"
        "    Altitude FLOAT,\n"
        "    RateOfClimb FLOAT,\n"
        "\n"
        "  Heading FLOAT,\n"
        "  RateOfTurn INTEGER,\n"
        "\n"
        "  Throttle INTEGER,\n"
        "  Speed FLOAT\n"
        ");";

const char *connectionPragmaCommand = "PRAGMA journal_mode = WAL;\n"
        "PRAGMA synchronous = NORMAL;";

const char *startNewFlightCommand = "INSERT INTO flights (start) VALUES (datetime('now'));";

#endif //FLIGHTMANAGER_DATABASECOMMANDS_H
