/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: communicationProtocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "communicationProtocol.pb-c.h"
void   waypoint__init
                     (Waypoint         *message)
{
  static Waypoint init_value = WAYPOINT__INIT;
  *message = init_value;
}
size_t waypoint__get_packed_size
                     (const Waypoint *message)
{
  assert(message->base.descriptor == &waypoint__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t waypoint__pack
                     (const Waypoint *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &waypoint__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t waypoint__pack_to_buffer
                     (const Waypoint *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &waypoint__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Waypoint *
       waypoint__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Waypoint *)
     protobuf_c_message_unpack (&waypoint__descriptor,
                                allocator, len, data);
}
void   waypoint__free_unpacked
                     (Waypoint *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &waypoint__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   route__init
                     (Route         *message)
{
  static Route init_value = ROUTE__INIT;
  *message = init_value;
}
size_t route__get_packed_size
                     (const Route *message)
{
  assert(message->base.descriptor == &route__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t route__pack
                     (const Route *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &route__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t route__pack_to_buffer
                     (const Route *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &route__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Route *
       route__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Route *)
     protobuf_c_message_unpack (&route__descriptor,
                                allocator, len, data);
}
void   route__free_unpacked
                     (Route *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &route__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   drone_message__position__init
                     (DroneMessage__Position         *message)
{
  static DroneMessage__Position init_value = DRONE_MESSAGE__POSITION__INIT;
  *message = init_value;
}
void   drone_message__gps_velocity__init
                     (DroneMessage__GpsVelocity         *message)
{
  static DroneMessage__GpsVelocity init_value = DRONE_MESSAGE__GPS_VELOCITY__INIT;
  *message = init_value;
}
void   drone_message__air_velocity__init
                     (DroneMessage__AirVelocity         *message)
{
  static DroneMessage__AirVelocity init_value = DRONE_MESSAGE__AIR_VELOCITY__INIT;
  *message = init_value;
}
void   drone_message__altitude__init
                     (DroneMessage__Altitude         *message)
{
  static DroneMessage__Altitude init_value = DRONE_MESSAGE__ALTITUDE__INIT;
  *message = init_value;
}
void   drone_message__attitude__init
                     (DroneMessage__Attitude         *message)
{
  static DroneMessage__Attitude init_value = DRONE_MESSAGE__ATTITUDE__INIT;
  *message = init_value;
}
void   drone_message__baro_data__init
                     (DroneMessage__BaroData         *message)
{
  static DroneMessage__BaroData init_value = DRONE_MESSAGE__BARO_DATA__INIT;
  *message = init_value;
}
void   drone_message__three_dimensional_data__init
                     (DroneMessage__ThreeDimensionalData         *message)
{
  static DroneMessage__ThreeDimensionalData init_value = DRONE_MESSAGE__THREE_DIMENSIONAL_DATA__INIT;
  *message = init_value;
}
void   drone_message__battery_data__init
                     (DroneMessage__BatteryData         *message)
{
  static DroneMessage__BatteryData init_value = DRONE_MESSAGE__BATTERY_DATA__INIT;
  *message = init_value;
}
void   drone_message__command_set__init
                     (DroneMessage__CommandSet         *message)
{
  static DroneMessage__CommandSet init_value = DRONE_MESSAGE__COMMAND_SET__INIT;
  *message = init_value;
}
void   drone_message__command_update__init
                     (DroneMessage__CommandUpdate         *message)
{
  static DroneMessage__CommandUpdate init_value = DRONE_MESSAGE__COMMAND_UPDATE__INIT;
  *message = init_value;
}
void   drone_message__init
                     (DroneMessage         *message)
{
  static DroneMessage init_value = DRONE_MESSAGE__INIT;
  *message = init_value;
}
size_t drone_message__get_packed_size
                     (const DroneMessage *message)
{
  assert(message->base.descriptor == &drone_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t drone_message__pack
                     (const DroneMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &drone_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t drone_message__pack_to_buffer
                     (const DroneMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &drone_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DroneMessage *
       drone_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DroneMessage *)
     protobuf_c_message_unpack (&drone_message__descriptor,
                                allocator, len, data);
}
void   drone_message__free_unpacked
                     (DroneMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &drone_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor waypoint__field_descriptors[7] =
{
  {
    "timestamp",
    200,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(Waypoint, has_timestamp),
    offsetof(Waypoint, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latitude",
    201,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Waypoint, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    202,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Waypoint, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    203,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Waypoint, altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orbit_radius",
    204,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Waypoint, has_orbit_radius),
    offsetof(Waypoint, orbit_radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orbit_until_target_altitude",
    205,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Waypoint, has_orbit_until_target_altitude),
    offsetof(Waypoint, orbit_until_target_altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orbit_clockwise",
    206,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Waypoint, has_orbit_clockwise),
    offsetof(Waypoint, orbit_clockwise),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned waypoint__field_indices_by_name[] = {
  3,   /* field[3] = altitude */
  1,   /* field[1] = latitude */
  2,   /* field[2] = longitude */
  6,   /* field[6] = orbit_clockwise */
  4,   /* field[4] = orbit_radius */
  5,   /* field[5] = orbit_until_target_altitude */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange waypoint__number_ranges[1 + 1] =
{
  { 200, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor waypoint__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Waypoint",
  "Waypoint",
  "Waypoint",
  "",
  sizeof(Waypoint),
  7,
  waypoint__field_descriptors,
  waypoint__field_indices_by_name,
  1,  waypoint__number_ranges,
  (ProtobufCMessageInit) waypoint__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor route__field_descriptors[2] =
{
  {
    "comment",
    210,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Route, comment),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "route",
    211,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Route, n_route),
    offsetof(Route, route),
    &waypoint__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned route__field_indices_by_name[] = {
  0,   /* field[0] = comment */
  1,   /* field[1] = route */
};
static const ProtobufCIntRange route__number_ranges[1 + 1] =
{
  { 210, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor route__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Route",
  "Route",
  "Route",
  "",
  sizeof(Route),
  2,
  route__field_descriptors,
  route__field_indices_by_name,
  1,  route__number_ranges,
  (ProtobufCMessageInit) route__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drone_message__position__field_descriptors[6] =
{
  {
    "timestamp",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(DroneMessage__Position, has_timestamp),
    offsetof(DroneMessage__Position, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "real_time",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DroneMessage__Position, has_real_time),
    offsetof(DroneMessage__Position, real_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latitude",
    22,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__Position, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    23,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__Position, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gps_altitude",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SFIXED32,
    offsetof(DroneMessage__Position, has_gps_altitude),
    offsetof(DroneMessage__Position, gps_altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "number_of_satellites",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(DroneMessage__Position, has_number_of_satellites),
    offsetof(DroneMessage__Position, number_of_satellites),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drone_message__position__field_indices_by_name[] = {
  4,   /* field[4] = gps_altitude */
  2,   /* field[2] = latitude */
  3,   /* field[3] = longitude */
  5,   /* field[5] = number_of_satellites */
  1,   /* field[1] = real_time */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange drone_message__position__number_ranges[2 + 1] =
{
  { 20, 0 },
  { 25, 4 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor drone_message__position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DroneMessage.Position",
  "Position",
  "DroneMessage__Position",
  "",
  sizeof(DroneMessage__Position),
  6,
  drone_message__position__field_descriptors,
  drone_message__position__field_indices_by_name,
  2,  drone_message__position__number_ranges,
  (ProtobufCMessageInit) drone_message__position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drone_message__gps_velocity__field_descriptors[3] =
{
  {
    "timestamp",
    30,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__GpsVelocity, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    31,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__GpsVelocity, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "course_over_ground",
    32,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__GpsVelocity, course_over_ground),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drone_message__gps_velocity__field_indices_by_name[] = {
  2,   /* field[2] = course_over_ground */
  1,   /* field[1] = speed */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange drone_message__gps_velocity__number_ranges[1 + 1] =
{
  { 30, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor drone_message__gps_velocity__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DroneMessage.GpsVelocity",
  "GpsVelocity",
  "DroneMessage__GpsVelocity",
  "",
  sizeof(DroneMessage__GpsVelocity),
  3,
  drone_message__gps_velocity__field_descriptors,
  drone_message__gps_velocity__field_indices_by_name,
  1,  drone_message__gps_velocity__number_ranges,
  (ProtobufCMessageInit) drone_message__gps_velocity__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drone_message__air_velocity__field_descriptors[2] =
{
  {
    "timestamp",
    40,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(DroneMessage__AirVelocity, has_timestamp),
    offsetof(DroneMessage__AirVelocity, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    41,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__AirVelocity, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drone_message__air_velocity__field_indices_by_name[] = {
  1,   /* field[1] = speed */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange drone_message__air_velocity__number_ranges[1 + 1] =
{
  { 40, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor drone_message__air_velocity__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DroneMessage.AirVelocity",
  "AirVelocity",
  "DroneMessage__AirVelocity",
  "",
  sizeof(DroneMessage__AirVelocity),
  2,
  drone_message__air_velocity__field_descriptors,
  drone_message__air_velocity__field_indices_by_name,
  1,  drone_message__air_velocity__number_ranges,
  (ProtobufCMessageInit) drone_message__air_velocity__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drone_message__altitude__field_descriptors[3] =
{
  {
    "timestamp",
    50,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(DroneMessage__Altitude, has_timestamp),
    offsetof(DroneMessage__Altitude, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    51,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__Altitude, altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rate_of_climb",
    52,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SFIXED32,
    offsetof(DroneMessage__Altitude, has_rate_of_climb),
    offsetof(DroneMessage__Altitude, rate_of_climb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drone_message__altitude__field_indices_by_name[] = {
  1,   /* field[1] = altitude */
  2,   /* field[2] = rate_of_climb */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange drone_message__altitude__number_ranges[1 + 1] =
{
  { 50, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor drone_message__altitude__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DroneMessage.Altitude",
  "Altitude",
  "DroneMessage__Altitude",
  "",
  sizeof(DroneMessage__Altitude),
  3,
  drone_message__altitude__field_descriptors,
  drone_message__altitude__field_indices_by_name,
  1,  drone_message__altitude__number_ranges,
  (ProtobufCMessageInit) drone_message__altitude__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drone_message__attitude__field_descriptors[4] =
{
  {
    "timestamp",
    60,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(DroneMessage__Attitude, has_timestamp),
    offsetof(DroneMessage__Attitude, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "course_magnetic",
    61,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__Attitude, course_magnetic),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pitch",
    62,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__Attitude, pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roll",
    63,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__Attitude, roll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drone_message__attitude__field_indices_by_name[] = {
  1,   /* field[1] = course_magnetic */
  2,   /* field[2] = pitch */
  3,   /* field[3] = roll */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange drone_message__attitude__number_ranges[1 + 1] =
{
  { 60, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor drone_message__attitude__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DroneMessage.Attitude",
  "Attitude",
  "DroneMessage__Attitude",
  "",
  sizeof(DroneMessage__Attitude),
  4,
  drone_message__attitude__field_descriptors,
  drone_message__attitude__field_indices_by_name,
  1,  drone_message__attitude__number_ranges,
  (ProtobufCMessageInit) drone_message__attitude__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drone_message__baro_data__field_descriptors[3] =
{
  {
    "timestamp",
    70,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__BaroData, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pressure",
    71,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__BaroData, pressure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature",
    72,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SFIXED32,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__BaroData, temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drone_message__baro_data__field_indices_by_name[] = {
  1,   /* field[1] = pressure */
  2,   /* field[2] = temperature */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange drone_message__baro_data__number_ranges[1 + 1] =
{
  { 70, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor drone_message__baro_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DroneMessage.BaroData",
  "BaroData",
  "DroneMessage__BaroData",
  "",
  sizeof(DroneMessage__BaroData),
  3,
  drone_message__baro_data__field_descriptors,
  drone_message__baro_data__field_indices_by_name,
  1,  drone_message__baro_data__number_ranges,
  (ProtobufCMessageInit) drone_message__baro_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drone_message__three_dimensional_data__field_descriptors[4] =
{
  {
    "timestamp",
    80,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__ThreeDimensionalData, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    81,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__ThreeDimensionalData, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    82,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__ThreeDimensionalData, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    83,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__ThreeDimensionalData, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drone_message__three_dimensional_data__field_indices_by_name[] = {
  0,   /* field[0] = timestamp */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
  3,   /* field[3] = z */
};
static const ProtobufCIntRange drone_message__three_dimensional_data__number_ranges[1 + 1] =
{
  { 80, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor drone_message__three_dimensional_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DroneMessage.ThreeDimensionalData",
  "ThreeDimensionalData",
  "DroneMessage__ThreeDimensionalData",
  "",
  sizeof(DroneMessage__ThreeDimensionalData),
  4,
  drone_message__three_dimensional_data__field_descriptors,
  drone_message__three_dimensional_data__field_indices_by_name,
  1,  drone_message__three_dimensional_data__number_ranges,
  (ProtobufCMessageInit) drone_message__three_dimensional_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drone_message__battery_data__field_descriptors[3] =
{
  {
    "timestamp",
    90,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(DroneMessage__BatteryData, has_timestamp),
    offsetof(DroneMessage__BatteryData, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage",
    91,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__BatteryData, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current",
    92,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__BatteryData, current),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drone_message__battery_data__field_indices_by_name[] = {
  2,   /* field[2] = current */
  0,   /* field[0] = timestamp */
  1,   /* field[1] = voltage */
};
static const ProtobufCIntRange drone_message__battery_data__number_ranges[1 + 1] =
{
  { 90, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor drone_message__battery_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DroneMessage.BatteryData",
  "BatteryData",
  "DroneMessage__BatteryData",
  "",
  sizeof(DroneMessage__BatteryData),
  3,
  drone_message__battery_data__field_descriptors,
  drone_message__battery_data__field_indices_by_name,
  1,  drone_message__battery_data__number_ranges,
  (ProtobufCMessageInit) drone_message__battery_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drone_message__command_set__field_descriptors[4] =
{
  {
    "timestamp",
    100,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(DroneMessage__CommandSet, has_timestamp),
    offsetof(DroneMessage__CommandSet, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yaw",
    101,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__CommandSet, yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pitch",
    102,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__CommandSet, pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thrust",
    103,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(DroneMessage__CommandSet, thrust),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drone_message__command_set__field_indices_by_name[] = {
  2,   /* field[2] = pitch */
  3,   /* field[3] = thrust */
  0,   /* field[0] = timestamp */
  1,   /* field[1] = yaw */
};
static const ProtobufCIntRange drone_message__command_set__number_ranges[1 + 1] =
{
  { 100, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor drone_message__command_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DroneMessage.CommandSet",
  "CommandSet",
  "DroneMessage__CommandSet",
  "",
  sizeof(DroneMessage__CommandSet),
  4,
  drone_message__command_set__field_descriptors,
  drone_message__command_set__field_indices_by_name,
  1,  drone_message__command_set__number_ranges,
  (ProtobufCMessageInit) drone_message__command_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor drone_message__command_update__field_descriptors[8] =
{
  {
    "pitch_angle",
    110,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(DroneMessage__CommandUpdate, vertical_command_case),
    offsetof(DroneMessage__CommandUpdate, pitch_angle),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    111,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DroneMessage__CommandUpdate, vertical_command_case),
    offsetof(DroneMessage__CommandUpdate, altitude),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rate_of_climb",
    112,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(DroneMessage__CommandUpdate, vertical_command_case),
    offsetof(DroneMessage__CommandUpdate, rate_of_climb),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heading",
    113,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(DroneMessage__CommandUpdate, horizontal_command_case),
    offsetof(DroneMessage__CommandUpdate, heading),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rate_of_turn",
    114,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(DroneMessage__CommandUpdate, horizontal_command_case),
    offsetof(DroneMessage__CommandUpdate, rate_of_turn),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "throttle",
    115,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DroneMessage__CommandUpdate, speed_command_case),
    offsetof(DroneMessage__CommandUpdate, throttle),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    116,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DroneMessage__CommandUpdate, speed_command_case),
    offsetof(DroneMessage__CommandUpdate, speed),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    120,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(DroneMessage__CommandUpdate, has_timestamp),
    offsetof(DroneMessage__CommandUpdate, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drone_message__command_update__field_indices_by_name[] = {
  1,   /* field[1] = altitude */
  3,   /* field[3] = heading */
  0,   /* field[0] = pitch_angle */
  2,   /* field[2] = rate_of_climb */
  4,   /* field[4] = rate_of_turn */
  6,   /* field[6] = speed */
  5,   /* field[5] = throttle */
  7,   /* field[7] = timestamp */
};
static const ProtobufCIntRange drone_message__command_update__number_ranges[2 + 1] =
{
  { 110, 0 },
  { 120, 7 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor drone_message__command_update__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DroneMessage.CommandUpdate",
  "CommandUpdate",
  "DroneMessage__CommandUpdate",
  "",
  sizeof(DroneMessage__CommandUpdate),
  8,
  drone_message__command_update__field_descriptors,
  drone_message__command_update__field_indices_by_name,
  2,  drone_message__command_update__number_ranges,
  (ProtobufCMessageInit) drone_message__command_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue drone_message__flight_mode__enum_values_by_number[5] =
{
  { "m_off", "DRONE_MESSAGE__FLIGHT_MODE__m_off", 0 },
  { "m_degraded", "DRONE_MESSAGE__FLIGHT_MODE__m_degraded", 1 },
  { "m_passThrough", "DRONE_MESSAGE__FLIGHT_MODE__m_passThrough", 2 },
  { "m_flybywire", "DRONE_MESSAGE__FLIGHT_MODE__m_flybywire", 3 },
  { "m_autonomous_return_to_base", "DRONE_MESSAGE__FLIGHT_MODE__m_autonomous_return_to_base", 4 },
};
static const ProtobufCIntRange drone_message__flight_mode__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex drone_message__flight_mode__enum_values_by_name[5] =
{
  { "m_autonomous_return_to_base", 4 },
  { "m_degraded", 1 },
  { "m_flybywire", 3 },
  { "m_off", 0 },
  { "m_passThrough", 2 },
};
const ProtobufCEnumDescriptor drone_message__flight_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DroneMessage.FlightMode",
  "FlightMode",
  "DroneMessage__FlightMode",
  "",
  5,
  drone_message__flight_mode__enum_values_by_number,
  5,
  drone_message__flight_mode__enum_values_by_name,
  1,
  drone_message__flight_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor drone_message__field_descriptors[19] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(DroneMessage, has_timestamp),
    offsetof(DroneMessage, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_mode",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(DroneMessage, has_current_mode),
    offsetof(DroneMessage, current_mode),
    &drone_message__flight_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_groundspeed",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, current_groundspeed),
    &drone_message__gps_velocity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_airspeed",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, current_airspeed),
    &drone_message__air_velocity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_position",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, current_position),
    &drone_message__position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_attitude",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, current_attitude),
    &drone_message__attitude__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "do_pressure_compensation",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DroneMessage, has_do_pressure_compensation),
    offsetof(DroneMessage, do_pressure_compensation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "static_pressure",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, static_pressure),
    &drone_message__baro_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pitot_pressure",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, pitot_pressure),
    &drone_message__baro_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gyro_raw",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, gyro_raw),
    &drone_message__three_dimensional_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mag_raw",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, mag_raw),
    &drone_message__three_dimensional_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accel_raw",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, accel_raw),
    &drone_message__three_dimensional_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_battery_data",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, current_battery_data),
    &drone_message__battery_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_command_set",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, output_command_set),
    &drone_message__command_set__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_command",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, current_command),
    &drone_message__command_update__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input_command",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, input_command),
    &drone_message__command_update__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sea_level_pressure",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DroneMessage, has_sea_level_pressure),
    offsetof(DroneMessage, sea_level_pressure),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "home_base",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, home_base),
    &waypoint__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "current_altitude",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DroneMessage, current_altitude),
    &drone_message__altitude__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned drone_message__field_indices_by_name[] = {
  11,   /* field[11] = accel_raw */
  3,   /* field[3] = current_airspeed */
  18,   /* field[18] = current_altitude */
  5,   /* field[5] = current_attitude */
  12,   /* field[12] = current_battery_data */
  14,   /* field[14] = current_command */
  2,   /* field[2] = current_groundspeed */
  1,   /* field[1] = current_mode */
  4,   /* field[4] = current_position */
  6,   /* field[6] = do_pressure_compensation */
  9,   /* field[9] = gyro_raw */
  17,   /* field[17] = home_base */
  15,   /* field[15] = input_command */
  10,   /* field[10] = mag_raw */
  13,   /* field[13] = output_command_set */
  8,   /* field[8] = pitot_pressure */
  16,   /* field[16] = sea_level_pressure */
  7,   /* field[7] = static_pressure */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange drone_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 19 }
};
const ProtobufCMessageDescriptor drone_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DroneMessage",
  "DroneMessage",
  "DroneMessage",
  "",
  sizeof(DroneMessage),
  19,
  drone_message__field_descriptors,
  drone_message__field_indices_by_name,
  1,  drone_message__number_ranges,
  (ProtobufCMessageInit) drone_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
